# Generated by Django 4.1.3 on 2022-12-02 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prgm_name', models.CharField(max_length=250)),
                ('loc_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.locations')),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=250)),
                ('loc_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.locations')),
                ('prgm_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.programs')),
            ],
        ),
    ]
