# Generated by Django 4.1.3 on 2022-12-08 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stud_id', models.AutoField(primary_key=True, serialize=False)),
                ('stud_name', models.CharField(max_length=30)),
                ('stud_phone', models.CharField(max_length=10)),
                ('stud_email', models.EmailField(max_length=100)),
                ('stud_address', models.CharField(max_length=100)),
                ('stud_place', models.CharField(max_length=100)),
            ],
        ),
    ]
