# Generated by Django 4.1.3 on 2022-12-12 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_coursesadd'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.coursesadd'),
        ),
    ]
